### PR TITLE
fixed #1

### LINKED ISSUE #1: Add parameter to filter by File Type
Let's call it `@FileTypes` which will accept the following values:

- ROWS
- LOG
- ALL

With the exception of `ALL` (**which should also be the default**), it should match the `type_desc` column of the [sys.master_files](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-master-files-transact-sql) and [sys.database_files](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-files-transact-sql) system tables.

It should be used for specifying the file types which we want to manage using the procedure.

### PR DESCRIPTION
**Pull request by evya696**

### CODE REVIEW

File: DatabaseFileSizeMaintenance.sql [hunk 1]
```diff
@@ -13,19 +13,21 @@ License
...
-,@MinFileSizeToShrinkMB			INT = 50000	-- if size smaller than thi  s, will not shrink
-,@MinDatabaseAgeInDays			INT = 30	-- databases must be at least this old to be checked
-,@TargetShrinkSizePercent		INT = 33	-- when shrinking, try to shrink down to this percentage of current file size
-,@MinTargetShrinkSizeMB			INT = 64	-- prevent shrinking to a size smaller than this
-,@ShrinkAllowReorganize			BIT = 1		-- set whether to allow reorganizing pages during shrink
-,@DatabaseOrder				NVARCHAR(max) = NULL
-,@DatabasesInParallel			NVARCHAR(max) = 'N'
-,@LogToTable				NVARCHAR(max) = 'Y'
-,@Execute				NVARCHAR(max) = 'Y'
+ CREATE OR ALTER PROCEDURE [dbo].[DatabaseFileSizeMaintenance]
```
Comment (EitanBlumin) [inline DatabaseFileSizeMaintenance.sql]: @evya696 , please change the command to `ALTER` only.
This is because only newer SQL versions support the `CREATE OR ALTER` syntax, and we want maximum backward compatibility.

**Review by EitanBlumin — CHANGES_REQUESTED** [review]

File: DatabaseFileSizeMaintenance.sql (hunk 1 above)
Comment (EitanBlumin) [reply DatabaseFileSizeMaintenance.sql]: Thanks
